### ISSUE TITLE
In single file mode, input file path is overwritten by output file path.

### ISSUE THREAD

**Issue by Zoltanar** [Kelebek1/Eushully-Decompiler#1]
Looks like the issue is here:
https://github.com/Kelebek1/Eushully-Decompiler/blob/d69d2fde11d06fa9fd5253fdafc43fc5e54a33b2/Decompiler/age-asm.cpp#L166

The output path is being added to the list instead of the input.

**Comment by Kelebek1** [comment]
Fixed in https://github.com/Kelebek1/Eushully-Decompiler/commit/8f0e8bba0b8373f1ec1e26b53f2b665a14b0b6fb
