### ISSUE TITLE
Requesting for a old tool for an issue you figured out 7 years ago about Kirikiri issue with repacking.

### ISSUE THREAD

**Issue by H0R1Z0N** [Kelebek1/Eushully-Decompiler#3]
Hi, i am currently trying to help the guys doing the Yosuga no sora translation, i was able to get byteshift the code back into it original value for everything under data.xp3. Sadly, it seem the dang compression back to anything like data.xp3 or patch.xp3 fail with the same error than OP in that thread and you had figured it out with a custom tool. Would it be possible for you to open source the tool or provide a exe ? From the following thread on fuwanovel : 

https://forums.fuwanovel.net/topic/7071-help-with-extraction-and-repacking-kirikiri/

Thank. HerbalNekoTea from Broken Dragon Translation, trying to make the Yosuga no Sora translation project happen for their group on discord.

PS : Used AE Tool to byteshift the value and grep the one with the readable stuff, then the metadata gave it away faster for the other stuff in the engine. I was able to get everything unencrypted fine. It's just any packing fail, either with stock file or modified one, i noticed when you byteshift again the file, the same file value with AE Tool will be the correct one. My math class about it was from a long time ago, so i am a bit rusted about it.

**Comment by Kelebek1** [comment]
That's from 2014, so everything there is looooong ago. I don't have any of it anymore and I don't remember anything about what I did, sorry. I'm not sure what you mean about being the right value in AE Tool, it looks like I didn't give out any script in that thread, so I'm not sure what you're comparing.

What's the discord?

**Comment by H0R1Z0N** [comment]
Well, since that post, i was able to unencrypt the asset and convert the
text in a working format and have the engine not use encryption. Sadly, it
seem to throwing me an error on a certain spot in the process. Let's me ask
then if i can share the discord link. I will reply in a few minute to hour.

**Comment by H0R1Z0N** [comment]
Here's the link. https://discord.gg/UNNE6Eg3
